version: "3"

services:
  app:
    build: .
    restart: unless-stopped
    # ports:
    #   - "80:80"
    environment:
      VIRTUAL_HOST: "lars-rickert.de"
      LETSENCRYPT_HOST: "lars-rickert.de"

networks:
  default:
    name: nginx-proxy
    external: true
